### ISSUE TITLE
Pronto-Swiftlint shows Errno::ENOENT in circleci

### ISSUE THREAD

**Issue by ase-wtag** [ajanauskas/pronto-swiftlint#3]
```yml
docker:
      - image: circleci/ruby:2.4.2
    steps:
      - run:
          name: Install cmake
          command: sudo apt-get install cmake
      - run:
          name: Install Pronto
          command: gem install pronto pronto-swiftlint
      - checkout
      - run:
          name: Unshallow git repo
          command: "[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow"
      - run:
          name: Run Pronto
          command: "PRONTO_GITHUB_ACCESS_TOKEN=$GITHUB_TOKEN PRONTO_PULL_REQUEST_ID=$(echo $CI_PULL_REQUEST | grep -o -E '[0-9]+$') pronto run -f github_status github_pr -c origin/master"
```

this shows the following error:
```bash
/usr/local/lib/ruby/2.4.0/open3.rb:199:in `spawn': No such file or directory - swiftlint (Errno::ENOENT)
	from /usr/local/lib/ruby/2.4.0/open3.rb:199:in `popen_run'
	from /usr/local/lib/ruby/2.4.0/open3.rb:95:in `popen3'
	from /usr/local/lib/ruby/2.4.0/open3.rb:258:in `capture3'
	from /usr/local/bundle/gems/pronto-swiftlint-0.2.0/lib/pronto/swiftlint/wrapper.rb:8:in `lint'
	from /usr/local/bundle/gems/pronto-swiftlint-0.2.0/lib/pronto/swiftlint_runner.rb:9:in `run'
	from /usr/local/bundle/gems/pronto-0.9.5/lib/pronto/runners.rb:20:in `block in run'
	from /usr/local/bundle/gems/pronto-0.9.5/lib/pronto/runners.rb:13:in `each'
	from /usr/local/bundle/gems/pronto-0.9.5/lib/pronto/runners.rb:13:in `run'
	from /usr/local/bundle/gems/pronto-0.9.5/lib/pronto.rb:64:in `run'
	from /usr/local/bundle/gems/pronto-0.9.5/lib/pronto/cli.rb:61:in `block in run'
	from /usr/local/bundle/gems/pronto-0.9.5/lib/pronto/cli.rb:60:in `chdir'
	from /usr/local/bundle/gems/pronto-0.9.5/lib/pronto/cli.rb:60:in `run'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /usr/local/bundle/gems/pronto-0.9.5/bin/pronto:6:in `<top (required)>'
	from /usr/local/bundle/bin/pronto:23:in `load'
	from /usr/local/bundle/bin/pronto:23:in `<main>'
Exited with code 1
```

What should be the issue with open3.rb?

Thanks in advance.
